<?php
/**
 * Created by PhpStorm.
 * User: flinnt-php-6
 * Date: 10/11/16
 * Time: 2:51 PM
 */

namespace Flinnt\Core\Queue\SMS;


use Illuminate\Queue\Queue;

/**
 * Class AbstractSMSQueue
 *
 * @package Flinnt\Core\Queue\SMS
 */
abstract class AbstractSMSQueue extends Queue
{

	/**
	 * Create a payload string from the given job and data.
	 *
	 * @param  string $job
	 * @param  mixed  $data
	 * @param  string $queue
	 *
	 * @return array
	 *
	 * @throws \InvalidArgumentException
	 */
	protected function createPayload( $job, $data = '', $queue = null )
	{
		return array_merge($data, ['message_text' => (String) $job]);
	}

	/**
	 * Create a typical, "plain" queue payload array.
	 *
	 * @param  string $job
	 * @param  mixed  $data
	 *
	 * @return array
	 */
	protected function createPlainPayload( $job, $data )
	{
		return parent::createPlainPayload($job, $data); // TODO: Change the autogenerated stub
	}


}